name: Triage new issues to Oncall board

on:
  issues:
    types: [opened, reopened]

jobs:
  triage-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Dummy step
      run: |
        echo $GITHUB_ACTOR, $GITHUB_REPOSITORY, $GITHUB_WORKSPACE, $GITHUB_EVENT_NAME
